#!/usr/bin/env bash

# ~/.bash_profile: executed by bash(1) for login shells.
# What is .bash_profile and what is .bashrc and the difference between them:
# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

# Checking whether the shell is interactive or not and
# whether it's Bash or not. In case it's interactive
# and Bash, it will try source .bashrc in case it exists.
if [ -n "$PS1" ] && [ -n "$BASH_VERSION" ]; then
 	# include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	    source "$HOME/.bashrc"
    fi
fi